spring:
  datasource:
    url: jdbc:sqlite:ledger.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: never
  liquidbase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 5000
  tomcat:
    threads:
      max: 200
      min-spare: 10
